name: bumame_iap_flutter
description: Bumame IAP authentication and authorization helpers for Flutter web apps.
version: 0.1.0-alpha.2
publish_to: none
repository: https://github.com/Bumame/bumame-iap-flutter-sdk

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.6
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
